### ISSUE TITLE
Custom Advancements

### ISSUE THREAD

**Issue by bumpyJake** [hapily04/Skream#15]
Is it possible to have custom advancements created within a datapack work with this addon?

When using one in a skript it returns this error
https://pastes.dev/QLN7xlyX5W

**Comment by hotpocket184** [comment]
Currently you are unable to work with custom advancements from datapacks, but with the new update to Skream coming soon you will be able to.

**Comment by bumpyJake** [comment]
Thank you, is there an ETA on the update or is it unknown currently?

**Comment by hapily04** [comment]
Our estimate is 3 weeks on the high end, with a possibility of 1-2 weeks. However, it could take longer. Here's a link to the Trello so you can see everything we have planned: https://trello.com/b/qRgLbNlq/skream
