### ISSUE TITLE
skream is not working on paper spigot 1.17.1

### ISSUE THREAD

**Issue by Yeahnkuuun** [hapily04/Skream#2]
skream has auto-disabled on paper spigot 1.17.1 (newest)

Error is below
https://github.com/hapily04/Skream/files/7519652/error.txt

**Comment by hotpocket184** [comment]
Thank you for letting us know. We assure you that this problem will be fixed in a future update.

**Comment by hotpocket184** [comment]
The issue has been found and will be resolved. For now you will need Citizens in order for Skream to work.
