### ISSUE TITLE
[Suggestion] Living Entity from NPC ID

### ISSUE THREAD

**Issue by EarthAgar** [hapily04/Skream#3]
Please add an expression to get the living entity of an npc / npc id. An example use of this is getting the entity and making it swing it's hand. You can't make an npc attack a block so being able to get the entity and then making that entity swing with Skript's effect would get around this.

**Comment by hapily04** [comment]
Added [ExprEntityFromNPC](https://github.com/hapily04/Skream/blob/master/src/main/java/us/happypockets/skream/elements/expressions/ExprEntityFromNPC.java) Thank you for the suggestion.

This will be publicly available with the next release of Skream.
