### ISSUE TITLE
Advancements

### ISSUE THREAD

**Issue by hotpocket184** [hapily04/Skream#8]
### Section

Advancements

### Content Additions

- Get All Advancements
- Condition to Check Advancements of a Player
- Effect to Grant an Advancement to a Player
- Effect to Revoke an Advancement from a Player
- Event to Check When an Advancement is Done
- Type for Advancements
- Custom Advancements

### Confirmation

- [x] I am a developer of Skream and are making valuable additions.

**Comment by hapily04** [comment]
Moving over to trello
